spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:boarddb

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google
            client-secret: google

jwt:
  issuer: appsog14@gmail.com
  secret_key: spring-study